---
authors:
  - name: Juan-Pablo
    affiliation: Win Climate
bibliography: references.bib
reference-location: margin
fig-cap-location: top
format:
  html:
    page-layout: article
---

# Brooklyn residents who are highly energy burdened today

## Foreword

New York State’s Solar Tax Credit is the largest of several state incentives available to homeowners installing rooftop solar.[^1] The credit can pay for 25% of a residential rooftop solar installation, or $5,000, whichever is less.

[^1]: See NY Climate Scoping Plan Integration Analysis [@cac_scoping_integration_2022]

The **Residential Solar Tax Credit Reform Act** ([s3596]()/[a6739]()) updates the current tax credit to make it fully refundable, so that low-income homeowners and people living in disadvantaged communities can also benefit from this incentive.[^2] The Act also increases[^3] the tax credit amount to $10,000, which has not been updated since 2006.

[^2]: [§1]() of S3596/A6739 [@nysenate_2024] allows residents to receive the full incentive from the state, regardless how much they owe in income tax. Today, a homeowner installing a $20K system that owes $1K in taxes would only receive $1K, not the full $5K they are eligible for.

[^3]: The All-Electric Building Act of 2023 [@aeba_2023], a version of which was enacted in the state’s FY ’23–24 budget.

The solar-project-by-income percentages in Figure 1 and Section 3.1 are based on the Residential Solar-Adopter Income and Demographic datasets from Lawrence Berkeley National Lab (lbnl), which counts the number of solar projects within each NYS county at each income level.

## Executive Summary

Analyzing solar installation data from nyserda and Lawrence Berkeley National Lab (*Table 1*), we find that:


-   **NY has a large rooftop solar gap**: homeowners with an annual income above $50,000 are **2.5x** more likely to have rooftop solar than those making below $50,000, who don’t always pay enough income tax to claim the full credit.
-   **NY’s solar tax credit is inequitable**: households making less than $50,000 make up **24%** of owner-occupied households in New York State, but have only received **5%** of the state’s residential tax credit subsidies.

::: column-margin
Table 1: Cost to New York State of implementing Bucks for Boilers, by year\

| Replacement year | Yearly cost (millions) |
|------------------|------------------------|
| 2025             | $548                  |
| 2026             | $1534                 |
| 2027             | $2,366                |
| 2028             | $3,260                |
| 2029             | $4,470                |
| 2030             | $4,837                |
:::

The following table contains a complete breakdown of our findings:

+-----------------------------+-------------------+------------------------+------------------------+
| Region                      | Homes with high \ | Avg. monthly energy\   | Avg. monthly savings\  |
|                             | energy burdens    | bills of high-burden \ | for high-burden homes\ |
|                             |                   | home                   | under NY HEAT          |
+=============================+===================+========================+========================+
| **Community District 4**\   | 23%               | $254                   | $128                   |
| Bushwick                    |                   |                        |                        |
+-----------------------------+-------------------+------------------------+------------------------+
| **Community District 11**\  | 28%               | $256                   | $123                   |
| Bensonhurst & Bath Beach    |                   |                        |                        |
+-----------------------------+-------------------+------------------------+------------------------+
| **Community District 16**\  | 35%               | $248                   | $144                   |
| Brownsville & Ocean Hill    |                   |                        |                        |
+-----------------------------+-------------------+------------------------+------------------------+
| **Community District 10**\  | 21%               | $279                   | $140                   |
| Bay Ridge & Dyker Heights   |                   |                        |                        |
+-----------------------------+-------------------+------------------------+------------------------+
| **Community District 1**\   | 18%               | $230                   | $113                   |
| Greenpoint & Williamsburg   |                   |                        |                        |
+-----------------------------+-------------------+------------------------+------------------------+
| **Community District 18**\  | 7%                | $385                   | $176                   |
| Canarsie & Flatlands        |                   |                        |                        |
+-----------------------------+-------------------+------------------------+------------------------+
| **Community District 14**\  | 22%               | $265                   | $123                   |
| Flatbush & Midwood          |                   |                        |                        |
+-----------------------------+-------------------+------------------------+------------------------+

What could be driving this “two tier” disparity (*Fig. 4*) in installation rates?

1.  High up-front costs. Solar panels are expensive, costing tens of thousands of dollars to install, so lower income people often can’t afford them.
2.  Low creditworthiness.
3.  Exclusion from tax credits.

Furthermore, 88% of these highly-burdened homeowners live in single family or low-rise multifamily buildings. Unlike residents of large multifamily buildings, where the savings from rooftop solar get diluted over many units, these households may be able to meaningfully cut their electricity bills by installing panels.

In total, making the tax credit fully refundable could benefit up to 63% of all highly energy-burdened families in New York.

# Findings

## Rooftop Solar Gap

While **25%** of all homeowners made less than $50,000 a year, these households installed only 10% of solar projects between 2010 and 2022. This is New York State’s **rooftop solar gap**.

If solar was being deployed equitably, we’d expect homeowners with annual incomes under $50,000 to receive a quarter of the state’s rooftop solar projects, not a tenth. Closing the solar gap would require growing these homeowners’ share of the solar installation pie by 2.5x.

### Unequal installation rates

To understand what’s behind New York’s inequitable distribution of rooftop solar, we must examine solar installation rates.

The contrast with higher-income households is striking: those with annual incomes above $50,000 are 2.5x more likely to have panels than those below.

But it is not the case that the higher a household’s income, the more likely they are to have solar panels on their roof. In fact, solar penetration rates are similar for all income buckets above $50,000, ranging from 22 to 27 households per project.'

### Discussion

What could be driving this “two tier” disparity in installation rates?

::: column-margin
{{< embed notebooks/analysis.qmd#fig-yearly-spending >}}
:::

High up-front costs: solar panels[^4] are expensive, costing tens of thousands of dollars to install, so lower income people often can’t afford them. The rise of solar leases, which allow homeowners to rent solar panels while paying nothing up-front, has significantly lowered up-front cost as an obstacle to adoption, however.

[^4]: The federal [Residential Clean Energy Credit]() administered by the IRS just received a 10-year extension through the Inflation Reduction Act.